name: NEuroDrAIn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - r-base
  - r-jsonlite
  - git
  - pip
  - pip:
    - tensorflow==2.12
    - git+https://reisert@bitbucket.org/reisert/patchwork.git
